# Site settings
name: "博客名"
title: 项目工作说明
motto: 关注产品、关注内容
email: 18686882@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://iuap3.githup.io/blog/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  iuap3

# timezone: Asia/Shanghai
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
liquid:
  error_mode: warn
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed
